name: techblog
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_spinkit: ^5.2.1
  go_router: ^14.7.2
  flutter_svg: ^2.2.1
  validators: ^3.0.0
  get: ^4.7.2
  share_plus: ^12.0.0
  url_launcher: ^6.3.2
  dio: ^5.9.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: any
  flutter_gen_runner: any

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: dana
      fonts:
        - asset: assets/fonts/DANA-BOLD.ttf
          weight: 700
        - asset: assets/fonts/DANA-REGULAR.ttf
          weight: 300
